output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  case-sensitive: true

linters:
  enable-all: true
  disable:
     # magic number detector (mnd) is too strict
    - mnd
  # TODO(https://github.com/nlnwa/warchaeology/issues/66): The following
  # sub-linters should be evaluated if they are going to be enabled or not.
    - containedctx
    - cyclop
    - depguard
    - errorlint
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - gocritic
    - godot
    - godox
    - gofumpt
    - gomnd
    - gosec
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - stylecheck
    - tenv
    - testifylint
    - testpackage
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
