# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    - ./script/completions.sh


builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
    binary: warc

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    rlcp: true
    files:
      - README.md
      - LICENSE
      - completions/*

nfpms:
  - vendor: National Library of Norway
    description: All things WARC
    homepage: https://nlnwa.github.io/warchaeology/
    license: Apache 2.0
    maintainer: John Erik Halse <john.halse@nb.no>
    file_name_template: '{{ .ConventionalFileName }}'
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/warc.bash
        dst: /usr/share/bash-completion/completions/warc
        file_info:
          mode: 0644
      - src: ./completions/warc.fish
        dst: /usr/share/fish/vendor_completions.d/warc.fish
        file_info:
          mode: 0644
      - src: ./completions/warc.zsh
        dst:  /usr/share/zsh/vendor-completions/_warc
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/warc/copyright
        file_info:
          mode: 0644
    overrides:
      rpm:
        replacements:
          amd64: x86_64
          arm64: aarch64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'typo'
