module.exports = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/installation']
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['guides/configuration', 'guides/hooks']
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference/cli' }]
    },
    'contributing'
  ]
};
